spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/stay_locked_in
spring.datasource.username=postgres
spring.datasource.password=1Sw@pnilsoni

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

#############################################
# JWT Configuration
#############################################

jwt.secret=StayLockedInSuperSecretJwtKeyForDevelopment12345678901234567890
jwt.expiration=86400000

#############################################
# CORS Configuration
#############################################

app.cors.allowed-origins=http://localhost:3000